/* ==========================================================
-- GRANTS DE MARGARITA1 → MARGARITA2 / MARGARITA3 / MARGARITA4
  ============================================================ */
GRANT SELECT, INSERT, UPDATE, DELETE ON SUCURSAL1   TO MARGARITA2, MARGARITA3, MARGARITA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON EMPLEADO1   TO MARGARITA2, MARGARITA3, MARGARITA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENTE1    TO MARGARITA2, MARGARITA3, MARGARITA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON VINO1       TO MARGARITA2, MARGARITA3, MARGARITA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON DISTRIBUYE1 TO MARGARITA2, MARGARITA3, MARGARITA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON SOLICITA1   TO MARGARITA2, MARGARITA3, MARGARITA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON REALIZA1    TO MARGARITA2, MARGARITA3, MARGARITA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUCTOR   TO MARGARITA2, MARGARITA3, MARGARITA4;
COMMIT;


/* UNA VEZ TODO COMPROBADO SOBRE LOS GRANTS PASAMOS A LAS VISTAS GLOBALES (SE EJECUTA EL MISMO CODIGO EN TODAS LAS LOCALIDADES */

/*SUCURSAL GLOBAL*/
CREATE OR REPLACE VIEW SUCURSAL_GLOBAL AS
SELECT * FROM MARGARITA1.SUCURSAL1
UNION ALL
SELECT * FROM MARGARITA2.SUCURSAL2
UNION ALL
SELECT * FROM MARGARITA3.SUCURSAL3
UNION ALL
SELECT * FROM MARGARITA4.SUCURSAL4;

/*CLIENTE GLOBAL*/
CREATE OR REPLACE VIEW CLIENTE_GLOBAL AS
SELECT * FROM MARGARITA1.CLIENTE1
UNION ALL
SELECT * FROM MARGARITA2.CLIENTE2
UNION ALL
SELECT * FROM MARGARITA3.CLIENTE3
UNION ALL
SELECT * FROM MARGARITA4.CLIENTE4;

/*EMPLEADO_GLOBAL*/
CREATE OR REPLACE VIEW EMPLEADO_GLOBAL AS
SELECT * FROM MARGARITA1.EMPLEADO1
UNION ALL
SELECT * FROM MARGARITA2.EMPLEADO2
UNION ALL
SELECT * FROM MARGARITA3.EMPLEADO3
UNION ALL
SELECT * FROM MARGARITA4.EMPLEADO4;

/*PRODUCTOR ESTA REPLICADA*/

/*VINO GLOBAL*/
CREATE OR REPLACE VIEW VINO_GLOBAL AS
SELECT * FROM MARGARITA1.VINO1
UNION ALL
SELECT * FROM MARGARITA2.VINO2
UNION ALL
SELECT * FROM MARGARITA3.VINO3
UNION ALL
SELECT * FROM MARGARITA4.VINO4;

/* DISTRIBUYE GLOBAL */
CREATE OR REPLACE VIEW DISTRIBUYE_GLOBAL AS
SELECT * FROM MARGARITA1.DISTRIBUYE1
UNION ALL
SELECT * FROM MARGARITA2.DISTRIBUYE2
UNION ALL
SELECT * FROM MARGARITA3.DISTRIBUYE3
UNION ALL
SELECT * FROM MARGARITA4.DISTRIBUYE4;

/*SOLICITA GLOBAL*/
CREATE OR REPLACE VIEW SOLICITA_GLOBAL AS
SELECT * FROM MARGARITA1.SOLICITA1
UNION ALL
SELECT * FROM MARGARITA2.SOLICITA2
UNION ALL
SELECT * FROM MARGARITA3.SOLICITA3
UNION ALL
SELECT * FROM MARGARITA4.SOLICITA4; 

/*REALIZA GLOBAL*/
CREATE OR REPLACE VIEW REALIZA_GLOBAL AS
SELECT * FROM MARGARITA1.REALIZA1
UNION ALL
SELECT * FROM MARGARITA2.REALIZA2
UNION ALL
SELECT * FROM MARGARITA3.REALIZA3
UNION ALL
SELECT * FROM MARGARITA4.REALIZA4; 

commit;



/*POR SI FALLA ALGUNA VISTA GLOBAL*/
DROP VIEW REALIZA_GLOBAL;
DROP VIEW SOLICITA_GLOBAL;
DROP VIEW DISTRIBUYE_GLOBAL;
DROP VIEW VINO_GLOBAL;
DROP VIEW PRODUCTOR_GLOBAL;
DROP VIEW EMPLEADO_GLOBAL;
DROP VIEW CLIENTE_GLOBAL;
DROP VIEW SUCURSAL_GLOBAL;

